firewall_v4_group_rules:
  201 allow http:
  - -A INPUT -p tcp --dport http -j ACCEPT
  202 teamspeak:
  - -A INPUT -p udp --dport 9987 -j ACCEPT
  - -A INPUT -p tcp --dport 10011 -j ACCEPT
  - -A INPUT -p tcp --dport 30033 -j ACCEPT
    
teamspeak_version: "3.0.13.2"

bm_upload_method: ftp
bm_upload_ftp_user: ftpuser
bm_upload_ftp_password: passwdftp
bm_upload_ftp_hosts: localhost
bm_upload_ftp_ttl: 5